services:
  app:
    image: my-app
    restart: unless-stopped
    ports: 
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - nats
    networks:
      - my_network


  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - "./sqlalchemy-postgres:/var/lib/postgresql/data"
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - "./sqlalchemy-pgadmin:/var/lib/pgadmin"
    depends_on:
      - postgres
    networks:
      - my_network

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"
    networks:
      - my_network
          
  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/data:/data
      - ./nats/config/server.conf:/config/server.conf
    networks:
      - my_network
 
 
  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    restart: unless-stopped
    ports:
      - "31311:31311"  
    volumes:
      - ./nui/db:/db
    depends_on:
      - nats
    networks:
      - my_network

networks:
  my_network:
    driver: bridge